Feature/#11
idoogroupdev/becupon_mobile pull request #3
Opened 2021-05-13 21:16 UTC by claudiarr93

issue 11: Integración de endpoints con la interfaz-Login

2021-05-14 20:08 UTC, idoogroupdev requested changes

2021-05-14 20:08 UTC, idoogroupdev commented on lib/src/provider/login_provider.dart
> +  String _url = "localhost:8000";
Tienes que leer esto desde la configuración

2021-05-18 23:05 UTC, claudiarr93 commented on lib/src/pages/coupons_information.dart
> +      child: Text('Shalom restaurant',
Ese campo no está en la API

2021-05-18 23:07 UTC, claudiarr93 commented on lib/src/pages/coupons_information.dart
> +    if (active != 0) results.addAll({'Cupones activos': '$active'});
Lo tendré en cuenta, tengo esa práctica en Android pero en Flutter tengo que revisar la forma de hacerlo para lograr la internacionañización.

2021-05-18 23:09 UTC, claudiarr93 commented on lib/main.dart
> +    uri: "http://localhost:8000/graphql/",
Voy a revisar cómo se puede hacer.

2021-05-18 23:11 UTC, claudiarr93 commented on lib/src/pages/coupons_information.dart
> +      child: Text('Shalom restaurant',
Ese campo no está en la API, por eso lo tuve que fijar. Me mantengo al tanto para cuando esté tomarlo dinámicamente.

2021-05-21 19:38 UTC, merged